require "spec_helper"

describe "Routing" do
  describe "Paths Generated by Custom Routes:" do
    it "has a path for the detailed metadata view for a document" do
      expect(:get => "/catalog/111/details").to route_to(:controller => "catalog", :action => "details", :id => "111")
    end

    it "has a path for downloading content related to an individual item" do
      expect(:get => "/catalog/111/download").to route_to(:controller => "catalog", :action => "download", :id => "111")
    end
  end
end
